### ISSUE TITLE
Negative stall cycles found in some configurations for scalesim

### ISSUE THREAD

**Issue by manishdash123** [scalesim-project/scale-sim-v2#100]
Hi Team,
While running Scalesim as part of one of the Labs of ECE 8803: Hardware Software Codesign course at Georgia Tech, I found some configs to report negative stall cycles by scale sim. 

It perhaps could be a potential bug, which might be present in the scalesim code.

![image](https://github.com/scalesim-project/scale-sim-v2/assets/31148348/ac110fb6-51b3-4845-a622-df8463ec1b97)

An example of this could be seen in the screenshot (hope it is visible).

**Comment by ritikraj7** [comment]
Hi @manishdash123, thanks for finding this error. Could you please provide the config and topology files you used to generate this output? I can reproduce the same output and take a look then. Thanks!

**Comment by ritikraj7** [comment]
Hi @manishdash123, the [commit](https://github.com/scalesim-project/scale-sim-v2/commit/d78b47704bf244a728768e028f178024eebc8c20) solves this issue. 

I am closing this issue for now. Please reopen this issue if it still see negative stall cycles.
