### ISSUE TITLE
Error in the dimensions of alexnet and yolo_tiny networks

### ISSUE THREAD

**Issue by SgrSrikar-191938** [scalesim-project/scale-sim-v2#102]
In the CONV2 layer of Alexnet.csv, the IFMAP size is 207 x 207 x 96, which needs to be modified to 27 x 27 x 96. Some inconsistencies are observed in the dimensions of IFMAP for  CONV1 in yolo_tiny.csv when compared with the same CSV file from the previous simulator version. In the earlier version of the simulator, the dimensions of IFMAP for CONV1 were mentioned as 416 x 416 x 3, but in the version v2, it is modified to 5 x 5 x 3. Please verify these modified dimensions and update them accordingly.

**Comment by ritikraj7** [comment]
Thanks for the observations. Alexnet.csv and yolo_tiny.csv has been updated accordingly.

**Comment by huwenao** [comment]
Hello, Alexnet's first layer of convolution is 55 x 55 x 96 after calculation, and 27 x 27 x 96 after pooling. May I ask how this pooling process is represented in the simulator, or is it not represented
