### ISSUE TITLE
Thank you for your open-source work. Can I set up multiple arrays in parallel?

### ISSUE THREAD

**Issue by zym1599** [scalesim-project/scale-sim-v2#103]
Thank you for your open-source work. Can I set up multiple arrays in parallel?

**Comment by mohanbing** [comment]
Having the same problem! Some information regarding this would be beneficial.

**Comment by ritikraj7** [comment]
Hi @zym1599 @mohanbing , please use [this repo](https://github.com/scalesim-project/krittika) for multiple arrays.
