### ISSUE TITLE
Any support for asynchronized communication?

### ISSUE THREAD

**Issue by robinren03** [scalesim-project/scale-sim-v2#105]
Does there exist support for asynchronized communication on NPU? If yes, how should I introduce the asynchronized communication (such as AllReduce and etc.) into workload?

Or more specifically, will a concurrent DRAM read/write operation affect the computation on the array?

**Comment by ritikraj7** [comment]
Hi @robinren03, the tool is specifically designed to simulate the compute behavior of a single core systolic array. You can use another tool from our lab called [astrasim](https://astra-sim.github.io) to model both communication and compute.

The tool does not simulate DRAM reads/writes. It only generates DRAM traces. You can use DRAM simulators like [DRAMsim](https://github.com/umd-memsys/DRAMsim3) along with scalesim to model the end-to-end behavior. You can use any DRAM simulator and need to convert the traces as per the format used by the simulator. 

Feel free to reopen the issue if you have any further questions.
