### ISSUE TITLE
Output result explanation

### ISSUE THREAD

**Issue by lovemyyuyu** [scalesim-project/scale-sim-v2#108]
Can you explain the calculation method and specific meaning of these two output parameters

![屏幕截图 2024-07-29 104617](https://github.com/user-attachments/assets/97cc8495-f104-428b-8e5a-929e1e42c2c7)

**Comment by ritikraj7** [comment]
I didn't understand your question. But if you are asking about mapping efficiency and overall utilization, the answer is:
Mapping efficiency: Percentage of PEs used during compute cycles
Overall utilization: Percenctage of PEs used during total cycles (including fill/drain cycles)
