### ISSUE TITLE
Eyeriss configuration

### ISSUE THREAD

**Issue by gksruf** [scalesim-project/scale-sim-v2#25]
Thanks for your kindness and great works.

At cfg file,
IfmapSramSzkB: 6144
FilterSramSzkB: 6144
OfmapSramSzkB: 2048
means that the processor SRAM size is (6144 + 6144 + 2048)?

At cfg of eyeriss, the sram size of (IA, W, OA) are 108, 108, 108 but eyeriss has only 108KB in total.
Moreover eyeriss has its register files in PE each. How the simulator handles it? (RF size, SRAM bandwidth)

**Comment by wxbbuaa2011** [comment]
Good question. expect answers.

**Comment by ritikraj7** [comment]
Hi @gksruf, For your first question, yes. Processor SRAM size is the summation of IfmapSramSzkB, FilterSramSzkB and OfmapSramSzkB.

For your second question, scalesim models eyeriss-like systolic array. This means it does not support register files in each PE. You might have noticed we don't support row stationary dataflow, which is used in eyeriss. The goal is to support IS, OS and WS data flows in a eyeriss-like systolic array (14x12). Regarding memory, you are correct. It has been updated now to be 36kB each.
