### ISSUE TITLE
Likely typo in `memory_map.py`

### ISSUE THREAD

**Issue by datMaffin** [scalesim-project/scale-sim-v2#29]
I just remembered that a while ago I noticed a very likely typo in `memory_map.py`.

The following line is probably missing a `:`:
https://github.com/scalesim-project/scale-sim-v2/blob/78919903a99d87824a106bedb54835dd8c557c00/scalesim/memory_map.py#L85

I.e., the line should be
```py
self.ifmap_map_list.append(elems[:self.num_banks])
```

While I do not understand the code 100%, I am pretty sure that the `:` is missing because there are very similar lines that come after that have a `:` in this position:
* https://github.com/scalesim-project/scale-sim-v2/blob/78919903a99d87824a106bedb54835dd8c557c00/scalesim/memory_map.py#L100
* https://github.com/scalesim-project/scale-sim-v2/blob/78919903a99d87824a106bedb54835dd8c557c00/scalesim/memory_map.py#L115

**Comment by ritikraj7** [comment]
Hi @datMaffin, thank you for pointing this out but currently we do not support memory mapping.
