### ISSUE TITLE
ISPASS documentation Figure 9.(b),(c)

### ISSUE THREAD

**Issue by jk98KR** [scalesim-project/scale-sim-v2#34]
I'm trying to reproduce ISPASS documentation's Figure 9.(b),(c) 
At the figure description which is right below the figure picture, it say's 2^14 MACs, 2^16 MACs for Fig9 (b),(c)

But, at the next page(P.65 ISPASS) "Figure 9(b-c) ~~~ 4096 and 16384 MAC units respectively" this makes me kinda confusing. (May be I misinterpreted it.) Can You give an advice for this?

Also, about reproducing TF0 layer has 31999 84 1024 (Sr, T, Sc) and considering it's 2^14 MACs(Figure 9.b) at R,C is 64x64 
I thought topofile should be in this format 
either 1 or 2
Layer name, IFMAP Height, IFMAP Width, Filter Height, Filter Width, Channels, Num Filter, Strides,
TF0,  64, 84,    64, 84,    250,      8,     1,               ...(1)
TF0,  16000, 84,    512, 84,    1,      1,     1,           ...(2)
(Maybe this could be wrong too. Sadly)  

I figured out basic tutorial how to run scale sim but having trouble setting the confis and topos. So can I ask You to give an topo file and config file for Figure 9.(b,c)? (for me to help understanding)

Thank you for Reading. 
Hope to get an answer for this.
Have a Good Day.

**Comment by AnandS09** [comment]
Hi @jk98KR , 

I am not sure I understood your question. As far as 2^14 and 2^16 MAC units are concerned they correspond to the compute capability of systolic arrays. It would be great if we can followup on the email. 

I am closing this issue as it is not related to tool or its functionality
