### ISSUE TITLE
variables mean

### ISSUE THREAD

**Issue by yun-lai-yun-qu** [scalesim-project/scale-sim-v2#36]
I want to know what these variables mean.Can you tell me?
in scale-sim-v2-main/scalesim/memory/read_buffer_estimate_bw.py
        # Tracking variables
        self.num_items_per_set = -1
        self.elems_current_set = 0
        self.current_set_id = 0
        self.read_buffer_set_start_id = -1
        self.read_buffer_set_end_id = -1
        self.prefetch_buffer_set_start_id = -1
        self.prefetch_buffer_set_end_id = -1
        self.last_prefetch_start_cycle = -2
        self.last_prefetch_end_cycle = -1
        self.first_request_rcvd_cycle = 0

**Comment by AnandS09** [comment]
Hi @yun-lai-yun-qu , 

These are internal tracking variables used in `read_buffer_estimate_bw.py`. We internally use set() datatypes to track and query the contents of the current SRAM state and what needs to be prefetched. Some of the variables also track the cycles at which prefetches are performed. 

I hope this clarifies your queries. 

Closing this issues as no further action is needed.
