### ISSUE TITLE
Error While Running Scalesim

### ISSUE THREAD

**Issue by clynnmathew** [scalesim-project/scale-sim-v2#37]
I am getting a TypeError while running Scalesim

Traceback (most recent call last):
  File "scalesim/scale.py", line 37, in <module>
    input_type_gemm=gemm_input
TypeError: __init__() got an unexpected keyword argument 'input_type_gemm'

Here is the command that I used
python3 scalesim/scale.py -c configs/scale.cfg -t topologies/conv_nets/yolo_tiny.csv -p OUTPUT

**Comment by Capser-Minyong** [comment]
do not use scalesim/scale.py, but use  python3 **<scale_sim_repo_root>**/scalesim/scale.py -c <path_to_config_file> -t <path_to_topology_file>

repo root is somewhere in your python site-packages directory

in my case, it is  
python3 /home/casper/.local/lib/python3.8/site-packages/scalesim/scale.py -c configs/scale.cfg -t topologies/conv_nets/yolo_tiny.csv

**Comment by AnandS09** [comment]
Hi @clynnmathew , 

Does @Capser-Minyong 's fix work for you? 

@Capser-Minyong : Thanks for pitching in :)

**Comment by Capser-Minyong** [comment]
> Hi @clynnmathew ,
> 
> Does @Capser-Minyong 's fix work for you?
> 
> @Capser-Minyong : Thanks for pitching in :)

Unfortunately, I also got same error message running scale-sim from git repo(I think scale-sim from pip installation is old version so I clone git repo). I think it is related to importing packages. 

Currently, I solve it with 3 modification : 

1.Run scale.py in <scale_sim_repo_root>/scalesim with following command:
python3 scale.py -c ../configs/scale.cfg -t ../topologies/conv_nets/Googlenet.csv -p ../output
(run in /home/casper/workspace/scale-sim-v2/scalesim)

2.scale.py
Line3 : from scalesim.scale_sim import scalesim -> from scale_sim import scalesim

3.scale_sim.py
Line3 : from scalesim.topology_utils import topologies -> from topology_utils import topologies

**Comment by AnandS09** [comment]
Hi @Capser-Minyong , thanks a lot for pointing this out. 

I have intended the scale.py file to be a quick example for getting up and started with the tool. 

**Quick note**: If scalesim package is already installed in your env then you can copy scale.py to any location and run it using `python3 scale.py -c <path to your config> -t <path to your topo>`

Also the name of the file does not have to be` scale.py.` . This file is just an example of how we can use the API to invoke the simulator. 

I am also open to suggestions on what you guys feel is a better place to put 'scale.py' in the repo such that confusions like this can be avoided.

Cheers
Anand
