### ISSUE TITLE
Number of SRAM reads for ofmap for input stationary dataflow is unrealistically small

### ISSUE THREAD

**Issue by boukhary123** [scalesim-project/scale-sim-v2#43]
The problem here is that number of reads for SRAM in ofmap for input stationary dataflow is unrealistically small. Upon inspection of the code, it seems that during the simulation the number of reads is not added to each other in each iteration of the output matrix. So instead the number of reads are overwriting each other so the final number of output reads becomes the number of reads of the last iteration. Hope this is clear.

**Comment by AnandS09** [comment]
Thanks @boukhary123 , I missed this issue here. Replicated the listing with more info in #44 .

Closing this by marking it as duplicate.
