### ISSUE TITLE
How do I check the bandwidth utilization of each layer of the network?

### ISSUE THREAD

**Issue by wxbbuaa2011** [scalesim-project/scale-sim-v2#46]
For example, Average IFMAP DRAM BW: 7.975 words/cycle, How do I know the bandwidth utilizaton?

**Comment by ritikraj7** [comment]
Hi @wxbbuaa2011, I am not sure what do you mean by bandwidth utilization. As far as I know, it is measured in bits/second. In the tool, one word is equal to 1 byte and you can specify clock cycle in seconds according to the processor speed. Feel free to follow up if this is not what you meant.
