### ISSUE TITLE
Tile size

### ISSUE THREAD

**Issue by nivi1501** [scalesim-project/scale-sim-v2#51]
Hi,
How do I get ofmap tile size (number of outputs generated in one iteration of DRAM)? Can you please point out the exact location in the code, where I can get an estimate about the total number of ofmap tiles as well as the size?

**Comment by ritikraj7** [comment]
Hi @nivi1501, you can refer to 'Avg OFMAP SRAM BW' in the file ../test_runs/<run_name>/<layer_no>/BANDWIDTH_REPORT.csv. It gives average words/cycle generated by the systolic array. Word size is 1 byte in scalesim. You can also refer to 'Avg OFMAP DRAM BW' in the same file to get an estimate of the number of words written each cycle by the OFMAP SRAM into DRAM.
