### ISSUE TITLE
 The "MemoryBanks" parameter in config tile *.cfg can only be set to 1?

### ISSUE THREAD

**Issue by bysg** [scalesim-project/scale-sim-v2#55]
In some case, maybe the memory banks can be more than1 to read or write sram with high bandwidht, but if i set "MemoryBanks" parameter in my config file, then there is error when run the python,

**Comment by dentionY** [comment]
> In some case, maybe the memory banks can be more than1 to read or write sram with high bandwidht, but if i set "MemoryBanks" parameter in my config file, then there is error when run the python,

PLS read line 80 in scale_config.py

**Comment by bysg** [comment]
> > In some case, maybe the memory banks can be more than1 to read or write sram with high bandwidht, but if i set "MemoryBanks" parameter in my config file, then there is error when run the python,
> 
> PLS read line 80 in scale_config.py

thanks a lot

**Comment by donghn** [comment]
Hi @bysg, @dentionY, Could you give me an example of the memory mapping configurations and the mapping files? Thanks

**Comment by bysg** [comment]
> Hi @bysg, @dentionY, Could you give me an example of the memory mapping configurations and the mapping files? Thanks

sorry, now i cannot run correctly with ("MemoryBanks" parameter > 1)
