### ISSUE TITLE
Can i get the tutorial3 script?

### ISSUE THREAD

**Issue by pixar0407** [scalesim-project/scale-sim-v2#56]
In the asplos tutorial, there is a tutorial 3 section.
But i cannot find the tutorial 3 script in this repository. 

In this repository, there are tutorial 1 and 2, but not 3.
So, can we get it?

**Comment by jmjos** [comment]
We did not publish this script, as is contains a lot of custom work for each user. You can follow the tutorial video and program it following your own requirements. We would therefore kindly refer you to the [video](https://www.youtube.com/watch?v=bHshg90aRvA).

You can also check out krittika for another template on the topic [here](https://github.com/scalesim-project/krittika)
