### ISSUE TITLE
Pipeline at MAC Unit

### ISSUE THREAD

**Issue by barut644** [scalesim-project/scale-sim-v2#61]
Firstly I would like to thank you for such this tool.
I wanted to ask a simple question. Is there anyway to simulate MAC unit that contains pipeline? For example I want to simulate systolic array that contains MAC units which gives output every 3 clock cycle.
Thank you

**Comment by ritikraj7** [comment]
Hi @barut644, the tool assumes a simple MAC unit that produces output every clock cycle. Modification inside MAC units is not supported by the tool. If you are only concerned about total number of cycles, you can update the variables for compute cycle to account for the fact that each MAC operation takes 3 clock cycles.
