### ISSUE TITLE
How to set the batch size in a training progress

### ISSUE THREAD

**Issue by KylePan-01** [scalesim-project/scale-sim-v2#65]
Hi, I want to use the simulator to simulate a training progress of a CNN for research purpose, but I'm confused about the batch size setting  in the simulator. Is it defaulted to 1 or other constent value? Furthermore, the simulation cycle of each layer in the output, I'm wondering its meaning. Does it mean training 1 data once through the CNN structure to get the weights costs that cycle?
Looking for anyone's reply and help me to use this simulator better.
Thanks very much!

**Comment by wangyuyue** [comment]
Hi,
According to #45, batching for convolution layers is not supported yet.
For the question

> Furthermore, the simulation cycle of each layer in the output, I'm wondering its meaning. Does it mean training 1 data once through the CNN structure to get the weights costs that cycle?
Can you elaborate on it in detail? I don't really understand.

**Comment by KylePan-01** [comment]
Hi,
Thanks for your answer for the first question. For the second question, as in the output, every layer has a simulation cycle for  certain input and weight size. However, I'm little confused about it. Does it means that the number of inputs to each layer is one? Or it's just meaning the number of input of the first layer is one and the following layers use feature maps according the struction(kernel number) of the CNN? Beacuase I want to use the simulation cycles to calculate an energy consumption of the CNN. I want to know the exact meaning of the value(cycle) in the output of each layer.
Looking for the reply!

**Comment by ritikraj7** [comment]
Hi @KylePan-01, the tool only simulates **inference**, not training. You can look at the topology file to see the exact input and weight size. The value(cycle) in simulator emulates one clock cycle in a real hardware.
