### ISSUE TITLE
Add a contributing.md

### ISSUE THREAD

**Issue by jmjos** [scalesim-project/scale-sim-v2#7]
Please add a contributing.md file following your wished how ppl should add code. Then, we can link it in the website. 

[Maybe just copy this example?](https://gist.github.com/PurpleBooth/b24679402957c63ec426) or a more complex [guide]( https://mozillascience.github.io/working-open-workshop/contributing/)

**Comment by AnandS09** [comment]
Anand: OK to close. Mortiz added the contributions.md
