### ISSUE TITLE
Where is the interface to DRAMsim2?

### ISSUE THREAD

**Issue by Z-KN** [scalesim-project/scale-sim-v2#71]
I only see the statistics given by the end of the simulation, whereas the paper reads "SCALE-SIM allows for modeling the main memory behavior by generating accurate read and write bandwidths at the interface, which can then be fed into a DRAM simulator e.g., DRAM-Sim2 [22]." So where do you dump the trace file to be fed into DRAMsim2? Or how could you invoke DRAMsim2?

**Comment by ritikraj7** [comment]
Hi @Z-KN, The trace file is by default dumped into the folder “../test_runs”. From there, you can use the DRAM traces as input to DRAMsim2. Conversion of these traces to DRAM-Sim2 formatting is out of the scope of this tool. The paper used in-house scripts and will not be open sourced.
