### ISSUE TITLE
Where is the MMIO and interrupt simulation?

### ISSUE THREAD

**Issue by Z-KN** [scalesim-project/scale-sim-v2#72]
In the paper, the authors claim that "The CPU is the bus master which interacts with the accelerator by writing task descriptors to memory-mapped registers inside the accelerator." And in Figure 1 there is an interrupt interface. However I cannot find corresponding code in this codebase. Could you care to point it out for me?

**Comment by ritikraj7** [comment]
Hi @Z-KN, the paper describes a model to integrate the accelerator in a system context. However, the interrupt interface is out of scope of this tool.
