### ISSUE TITLE
Why use ifmap_buf.get_hit_latency() for filter_hit_latency

### ISSUE THREAD

**Issue by lllbbbyyy** [scalesim-project/scale-sim-v2#74]
https://github.com/scalesim-project/scale-sim-v2/blob/08a984f11614ae04391ea5d2c8f54b14ad169e1e/scalesim/memory/double_buffered_scratchpad_mem.py#L161C34-L161C34

Is this intentional design or a mistake in writing the code？

**Comment by ritikraj7** [comment]
Hi @lllbbbyyy, thank for pointing that out. That was a mistake. This issue is fixed by #76 
Please also note that it does not affect default functionality because both the filter hit latency and ifmap hit latency are same by default.
