### ISSUE TITLE
How to generate the DRAM trace and the energy mentioned in the paper?

### ISSUE THREAD

**Issue by KylePan-01** [scalesim-project/scale-sim-v2#80]
<img width="530" alt="image" src="https://github.com/scalesim-project/scale-sim-v2/assets/45485890/dbe4bcc0-bba2-443b-a9fb-6036aec5c7c2">

Hi!
I want to use the DRAM traces within DRAMSys and the energy cost of the simulation training process.

Can anyone help me? 

Thanks a lot!

**Comment by pioneer0413** [comment]
Hello @KylePan-01, it seems you may have solved your question already. 

Though, I would like to introduce how to generate traces for someone not to waste their time in the future.

It's so simple. Just change boolean variable into `False` named `save_disk_space` at line 34 in `scale.py`.

Trace files occupy much more disk storage than the others. So I think it is set to off state by default.

Hope this would be helpful for you.
