### ISSUE TITLE
Can I change from  systolic array to 3D MAC NPU architecture  ?

### ISSUE THREAD

**Issue by Junhyuk** [scalesim-project/scale-sim-v2#97]

**Comment by ritikraj7** [comment]
Hi @Junhyuk, scale-sim is designed to simulate behavior of the simplest systolic array so that users have a clean baseline.
But SCALE-Sim-v2 can be modified to model the enhancements in the systolic array (i.e. 3D MAC NPU) as well, but that is not the goal of the base simulator.

**Comment by Junhyuk** [comment]
@ritikraj7  I understood !  thanks Ritik !

**Comment by zhouwq13** [comment]
> @ritikraj7 I understood ! thanks Ritik !

Hi, did you change to NPU architecture successfully?  I wonder if you can show me how to modify this, Thank you in advance !!!
